### ISSUE TITLE
Improve error message if Vale download fails

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs#16]
https://travis-ci.org/github/crate/cloud-getting-started/jobs/664347119?utm_medium=notification&utm_source=github_status

this is what happens when the vale git isn't responding. we could add a better error message here

**Comment by amotl** [comment]
As we've already moved off Travis CI, can we kondo this?

**Comment by mechanomi** [comment]
@amotl I don't think so. this is an issue with the Makefile itself not providing a useful message for the user when there is a network issue that causes the Vale download to fail. this is something that can happen to regular users. it's just that the issue also occurs when the PR checks run too sometimes
