### ISSUE TITLE
Silence Vale if there is no output

### ISSUE THREAD

**Issue by norosa** [crate/crate-docs#4]
at the moment, if there is nothing to report on, having lots and lots of Vale output looks sort of messy. it would be good to either shorten it to a single line (so you can see it is making progress)

**Comment by amotl** [comment]
This might have been improved through #46. Do you want to check that again, @mechanomi?

**Comment by mechanomi** [comment]
@amotl just checked this on master!!! wow, it's looking great!

I have one very minor suggestion. at the moment, `make lint-summary` produces:

```
$ make lint-summary
[]
"file","errors","warnings","suggestions"
```

the `[]` is output from the `jq` tool as it is producing the csv. and the next line is the csv itself. do we want to display the summary twice like this, in two different formats?

https://github.com/crate/crate-docs/blob/master/src/rules.mk#L200

if not, the first line can be silenced by appending `> /dev/null` the line above (verified locally)

**Comment by amotl** [comment]
> wow, it's looking great!

Thanks. After throwing away the file-by-file processing, I wanted to re-add this as I recognized you have been aiming at some sort of machine-readable summary output of Vale. I am glad you like it.

> Do we want to display the summary twice like this, in two different formats?

I wasn't sure about this and wanted to hear your opinion about it after demonstrating it to you. Actually, when running `make lint`, there is currently three types of output:
- Regular Vale output
- Summary in JSON format
- Summary in CSV format

Maybe we should just get rid of `cat`ing both of the latter and just echo a message about where these files have been manifested.

**Comment by mechanomi** [comment]
> Maybe we should just get rid of cating both of the latter and just echo a message about where these files have been manifested?

+1

**Comment by norosa** [comment]
this was fixed a while ago (Vale now only runs when you explicitly run `make check`)
